Algoritmo "MULTIPLOS-DE-DOIS"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Autor(a)    : LUCAS REGO ARAUJO
// Data atual  : 30/04/2022
Var
// Seção de Declarações das variáveis
j: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("### MULTIPLOS DE 2 ###")
para j de 0 ate 100 faca
     se (j % 2 = 0) entao
        escreval(j)
     fimse
fimpara


Fimalgoritmo