Algoritmo "SOMA100"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : LUCAS REGO ARAUJO
// Data atual  : 30/04/2022
Var
soma, j: inteiro


Inicio
soma <- 0
j <- 0

repita
      j <- j + 1
      soma <- soma + j
      
ate  j = 100

escreval("SOMA DOS 100 PRIMEIROS INTEIROS É IGUAL A: ", soma)


Fimalgoritmo